version: '3.1'
services:
  db_iBird:
    image: postgres:latest
    restart: always
    environment:
        POSTGRES_USER: admin
        POSTGRES_DB: iBird
        POSTGRES_PASSWORD: 123qwe
    ports:
      - 5432:5432